### PR TITLE
[UPSTREAM] Update GPU selection dropdown to only available GPUs

### PR DESCRIPTION
**Pull request by VaishnaviHire**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-3190
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

cc: @maroroman @LaVLaS @crobby

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Live Build is in Progress: https://rhods-jenkins-csb-livebuilds.apps.ocp-c1.prod.psi.redhat.com/job/rhods-livebuild/46/

**Comment by VaishnaviHire** [comment]
/hold until review from @lugi0 

Live Build: quay.io/modh/rhods-operator-live-catalog:1.9.0-rhods-3190

**Comment by lugi0** [comment]
Tested manually for now, with two nodes having 1 GPU each the dropdown shows only 1 GPU available (which is correct). Will do further testing and automation asap.

**Comment by lugi0** [comment]
Opened https://github.com/red-hat-data-services/ods-ci/pull/280 to automate TCs for this PR

**Review by LaVLaS — APPROVED** [review]
/lgtm

This worked for me when 2+ single gpu nodes where added to the server

**Pull request merged**
